spring:
  application:
    name: 140837-item-service
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      
       
  h2:
    console:
      enabled: true

server:
  port: 8081
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
    enabled: true
    fetch-registry: true 
    register-with-eureka: true
    
logging:
  level:
    org:
     hibernate:
      SQL: DEBUG
             
  