spring:  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect        
        
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.application_uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}
   