server:
  port: 64981
spring:  
  datasource:
    url:  jdbc:mysql://192.168.99.101:3306/productdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: my-Appian
    initialization-mode: always
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  resources:
    static-locations:
    - classpath:/static/images/catalogue/
          
          